### ISSUE TITLE
node-waf no longer included in Node/update to node-gyp

### ISSUE THREAD

**Issue by nosideeffects** [per-gron/emiflake#1]
Would it be possible to update emiflake to build with node-gyp and push the update to npm? I would really like to try it out in an app I am building on Heroku.

**Comment by per-gron** [comment]
Check out https://github.com/tomondev/emiflake

**Comment by andrewwakeling** [comment]
Any chance this can be pulled in?

**Comment by per-gron** [comment]
Done. (Sorry for being slow about this)
