### ISSUE TITLE
publish 1.0.1

### ISSUE THREAD

**Issue by alexgorbatchev** [per-gron/emiflake#2]
please publish 1.0.1 as 1.0.0 currently doesn't compile on node 0.10 and up

**Comment by chmanie** [comment]
Yes, please!

**Comment by alexgorbatchev** [comment]
Hey @pereckerdal, would you like some help in maintaining the module? I'd totally down for doing routine tasks like NPM publishing and merging PRs. Please let me know.

**Comment by alexgorbatchev** [comment]
published 1.1.0
